config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :tweets, except: [:edit, :update] do
    resources :comments, only: [:create, :destroy]
    member do
      post :retweet
    end
  end

  resources :profiles
  resources :likes, only: [:create]

  devise_for :users
  root to: 'tweets#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tweet_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_tweet_id  (tweet_id)
#  index_comments_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (tweet_id => tweets.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  include Likeable
  belongs_to :user
  belongs_to :tweet
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
    @comment = @tweet.comments.new(comment_params.merge(user: current_user))
    respond_to do |format|
      if @comment.save
        format.turbo_stream
      else
        format.html { redirect_to tweet_path(@tweet), alert: 'Reply could not be created' }
      end
    end
  end

  def destroy
    @comment = @tweet.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to tweet_path(@tweet), notice: 'Comment was deleted' }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<div class="py-4 border-b" id="<%= dom_id(comment)%>">
  <div class="flex space-x-3 items-start">
    <div>
      <%= profile_image(comment.user) %>
    </div>
    <div class="flex-1">
      <p class="font-bold"> <%= link_to comment.user.name, profile_path(comment.user), class: 'hover:underline', data: { turbo: false }%> </p>
      <div class="prose prose-lg"> <%= comment.body %> </div>
    
      <ul class="-ml-3 flex space-x-14 items-start justify-start list-none">
        <li>
          <%= content_tag :div, class: "#{dom_id(comment)}_likes" do %>
            <%= render "likes/likes", likeable: comment %>
          <% end %>
        </li>
        <% if user_signed_in? && current_user == comment.user  %>
          <li>
            <%= button_to tweet_comment_path(comment.tweet, comment), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "text-gray-500 space-x-2 group flex items-center justify-center" do %>
              <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-gray-50">
                <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current text-gray-500 group-hover:text-rose-500 w-5 h-5"><g><path d="M20.746 5.236h-3.75V4.25c0-1.24-1.01-2.25-2.25-2.25h-5.5c-1.24 0-2.25 1.01-2.25 2.25v.986h-3.75c-.414 0-.75.336-.75.75s.336.75.75.75h.368l1.583 13.262c.216 1.193 1.31 2.027 2.658 2.027h8.282c1.35 0 2.442-.834 2.664-2.072l1.577-13.217h.368c.414 0 .75-.336.75-.75s-.335-.75-.75-.75zM8.496 4.25c0-.413.337-.75.75-.75h5.5c.413 0 .75.337.75.75v.986h-7V4.25zm8.822 15.48c-.1.55-.664.795-1.18.795H7.854c-.517 0-1.083-.246-1.175-.75L5.126 6.735h13.74L17.32 19.732z"></path><path d="M10 17.75c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75zm4 0c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75z"></path></g></svg>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [tweet, @comment], data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset'} do |form| %>
  <p class="pt-3">Replying to <%= link_to tweet.user.name, profile_path(tweet.user), class: 'text-sky-500 hover:text-sky-600' %></p>
  <div class="flex items-center justify-between space-x-3 py-6 border-b">
    <%= profile_image(current_user) %>
    
    <div class="flex-1">
      <%= form.label :body, class: 'sr-only' %>
      <%= form.text_area :body, class: 'border-none w-full resize-none rounded-md focus:shadow-none focus:border-none ring-0 focus:ring-0 focus:outline-none text-lg py-3 px-0 h-full min-h[100px]', placeholder: 'Tweet your reply' %>
    </div>
    <%= form.submit 'Reply', class: 'px-6 py-2 bg-sky-400 text-white fornt-semibold rounded-full text-center cursor-pointer inline-block hover:bg-sky-500 transition ease-in-out duration-300' %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "#{dom_id(@tweet)}_comments" do %>
  <%= render 'comment', comment: @comment %>
<% end %>

<%= turbo_stream.update "#{dom_id(@tweet)}_comments_count" do %>
  <%= render 'tweets/comments_count', tweet: @tweet %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

<%= turbo_stream.update "#{dom_id(@tweet)}_comments_count" do %>
  <%= render 'tweets/comments_count', tweet: @tweet %>
<% end %>