config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :tweets, except: [:edit, :update] do
    resources :comments, only: [:create, :destroy]
    member do
      post :retweet
    end
  end

  resources :profiles
  resources :likes, only: [:create]

  devise_for :users
  root to: 'tweets#index'
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :bigint           not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tweet_id   :integer
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tweets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Tweet < ApplicationRecord
  include Likeable
  belongs_to :user
  belongs_to :tweet, optional: true
  has_many :comments

  validates :body, length: { maximum: 240 }, allow_blank: false, unless: :tweet_id

  def tweet_type
    if tweet_id? && body?
      'quote-tweet'
    elsif tweet_id?
      'retweet'
    else
      'tweet'
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.turbo_stream
      else
        format.html do 
          flash[:tweet_errors] = @tweet.errors.full_messages
          redirect_to root_path
        end
      end
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.order(created_at: :desc)
  end
  

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
  end

  def retweet
    @tweet = Tweet.find(params[:id])
    @retweet = current_user.tweets.new(tweet_id: @tweet.id)

    respond_to do |format|
      if @retweet.save
        format.turbo_stream
      else
        format.html { redirect_back fallback_location: @tweet, alert: 'Could not retweet' }
      end
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :tweet_id)
  end
end

app/views/tweets/_comments_count.html.erb
<span class="group-hover:text-sky-500 text-gray-500">
  <%= tweet.comments.count ||= 0 %>
</span>

app/views/tweets/_controls.html.erb
<ul class="-ml-3 flex space-x-14 items-start justify-start list-none">
  <li>
    <%= link_to tweet, class: 'text-gray-500 space-x-2 group flex items-center justify-center', data: { turbo: false } do %>
      <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-sky-50">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 group-hover:text-sky-500">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z" />
        </svg>
      </div>
      <%= turbo_frame_tag "#{dom_id(tweet)}_comments_count" do %>
        <% render 'tweets/comments_count', tweet: tweet %>
      <% end %>
    <% end %>

    <% if user_signed_in? && tweet.user_id != current_user.id %>
      <li>
        <%= button_to retweet_tweet_path(tweet), method: :post, class: 'text-gray-500 space-x-2 group flex items-center justify-center' do %>
          <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-green-50">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 group-hover:text-green-500">
              <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
            </svg>
          </div>
          <span class="group-hover:text-green-500 text-gray-500"><%= Tweet.where(tweet_id: tweet).count %></span>
        <% end %>
      </li>
    <% end %>

    <li>
      <%= content_tag :div, class: "#{dom_id(tweet)}_likes" do %>
        <%= render 'likes/likes', likeable: tweet %>
      <% end %>
    </li>

    <% if user_signed_in? && current_user == tweet.user %>
      <li>
        <%= button_to tweet_path(tweet), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'text-gray-500 space-x-2 group flex items-center justify-center' do %>
          <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-gray-50">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 group-hover:text-rose-500 text-gray-500">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
          </div>
        <% end %>
      </li>
    <% end %>

  </li>
</ul>

app/views/tweets/_empty.html.erb
<% if Tweet.all.none? %>
  <%= turbo_frame_tag Tweet.new do %>
    <div class="p-6">
      Nothing to see here ✨
    </div>
  <% end %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if flash[:tweet_errors] %>
    <div class="bg-red-50 text-red-500 px-2 py-2 font-medium rounded-lg mt-3 mx-3">
      <ul>
        <% flash[:tweet_errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_area :body, class: 'border-b border-t-0 border-x-0 mb-6 px-6 pt-6 block w-full border-gray-200 focus:shadow-none focus:outline-none focus:ring-transparent focus:border-gray-300 resize-none min-h-[180px] text-lg', placeholder: "What's on your mind? ✎" %>
  <div class='flex justify-end px-6 -mt-20'>
    <%= form.submit 'Tweet', class: 'px-6 py-2 bg-sky-400 text-white font-semibold rounded-full text-center cursor-pointer inline-block hover:bg-sky-500 trannsition ease-in-out duration-300'  %>
  </div>
<% end %>

app/views/tweets/_retweet.html.erb
<div class="px-6 py-3 border-b" id="<%= dom_id(tweet)%>">
  <div class="flex items-center mb-3 space-x-2">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15 15l6-6m0 0l-6-6m6 6H9a6 6 0 000 12h3" />
    </svg>
    <p class="text-sm font-medium">Retweeted by <%= '@' + tweet.user.username %></p>
  </div>
  <div class="flex space-x-3 items-start pb-3">
    <div class="flex-shrink-0">
      <%= profile_image(tweet.tweet.user) %>
    </div>
    <div class="flex-1">
      <p class="font-bold">
        <%= link_to tweet.tweet.user.name, profile_path(tweet.tweet.user), class: 'hover:underline', data: { turbo: false } %>
      </p>
      <div class="prose prose-lg"><%= tweet.tweet.body %></div>

      <%= render 'tweets/controls', tweet: tweet.tweet %>

    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="px-6 py-3" id="<%= dom_id(tweet)%>">
  <div class="flex space-x-3 items-start pb-3">
    <%= profile_image(tweet.user) %>
  </div>
  <div class="flex-1">
    <p class="font-bold">
      <%= link_to tweet.user.name, profile_path(tweet.user), class: 'hover:underline', data: { turbo: false } %>
    </p>
    <%= link_to tweet, data: { turbo: false } do %>
      <div class="prose prose-lg"><%= tweet.body %></div>
    <% end %>

    <%= render 'tweets/controls', tweet: tweet %>

  </div>
</div>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend 'tweets' do %>
  <%= render 'tweet', tweet: @tweet %>
<% end %>

<%= turbo_stream.update 'new_tweet_form' do %>
  <%= render 'form', tweet: Tweet.new %>
<% end %>

<%= turbo_stream.remove Tweet.new do %>
  <%= render 'tweets/empty' %>
<% end %>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream.remove @tweet %>

<%= turbo_stream.update "empty" do %>
  <%= render "tweets/empty" %>
<% end %>

app/views/tweets/index.html.erb
<div id="new_tweet_form" class="mb-8">
  <%= render partial: 'form', locals: { tweet: @tweet} %>
</div>

<%= turbo_frame_tag "tweets"  do %>
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/#{tweet.tweet_type}", locals: { tweet: tweet } %>
  <% end %>
<% end %>

<div id="empty">
  <%= render 'empty' %>
</div>

app/views/tweets/retweet.turbo_stream.erb
<%= turbo_stream.prepend 'tweets' do %>
  <%= render 'tweets/retweet', tweet: @retweet %>
<% end %>

app/views/tweets/show.html.erb
<div class="p-6">
  <div class="flex items-center space-x-3">
    <%= link_to root_path, class: "rounded-full w-8 h-8 flex items-center justify-center hover:bg-gray-100 duration-300 transition-all" do %>
      <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current text-gray-800 w-5 h-5"><g><path d="M20 11H7.414l4.293-4.293c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0l-6 6c-.39.39-.39 1.023 0 1.414l6 6c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L7.414 13H20c.553 0 1-.447 1-1s-.447-1-1-1z"></path></g></svg>
    <% end %>
    <h1 class="font-bold text-2xl">Bird Tweet</h1>
  </div>
</div>

<div class="p-6">
  <div class="flex items-start justify-between space-x-3">
    <%= profile_image(@tweet.user) %>
    <div class="flex-1">
      <h1 class="font-bold">
        <%= link_to @tweet.user.name, profile_path(@tweet.user) %>
      </h1>
      <p class="text-gray-700"><%= "@" + @tweet.user.username %></p>
    </div>
  </div>
  <div class="prose prose-2xl text-gray-900 my-3">
    <% if @tweet.tweet_id? %>
      <%= @tweet.tweet.body %>
    <% else%>
      <%= @tweet.body %>
    <% end %>
  </div>

  <ul class="py-3 border-t text-gray-700 flex space-x-4 text-sm">
    <li>
      <span class="font-semibold text-gray-800"><%= Tweet.where(tweet_id: @tweet).size %></span> Retweets
    </li>
    <li>
      <span class="font-semibold text-gray-800"><%= @tweet.likes.size %></span> Likes
    </li>
  </ul>

  <div class="py-2 border-y px-4 justify-center flex">
    <%= render "tweets/controls", tweet: @tweet %>
  </div>

  <% if user_signed_in? %>
    <%= turbo_frame_tag "#{dom_id(@tweet)}_comment_form" do %>
      <%= render "comments/form", tweet: @tweet %>
    <% end %>
  <% else %>
    <p class="mt-6 text-center text-lg"><%= link_to "Sign in", new_user_session_path, class: "text-sky-500 hover:text-sky-600 font-medium" %></p>
  <% end %>
  <%= turbo_frame_tag "#{dom_id(@tweet)}_comments" do %>
    <% @comments.each do |comment| %>
      <%= render "comments/comment", comment: comment %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag "#{dom_id(@tweet)}_comments" do %>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% end %>
</div>